Unmount command doesn't stop anymore on first failure
so that it can show the whole situation to the user. This way
user will see all the programs which will be closed if force option
is used.

diff --git a/system/bin/chroot-distro b/system/bin/chroot-distro
--- a/system/bin/chroot-distro
+++ b/system/bin/chroot-distro
@@ -909,6 +909,36 @@ chroot_distro_delete() {
     fi
 }
 
+chroot_distro_output_system_mount_point_paths() {
+    distro_path="$1"
+    storage_paths=$(
+        for file in "/storage"/*; do
+            echo "$distro_path$file"
+        done)
+    while read -r path_to_test; do
+        case "$path_to_test" in
+            *"$distro_path/data/"*) echo "$path_to_test" ;;
+            *"$distro_path/system/"*) echo "$path_to_test" ;;
+            *"$distro_path/sdcard/"*) echo "$path_to_test" ;;
+            *"$distro_path/dev/pts/"*) echo "$path_to_test" ;;
+            *"$distro_path/proc/"*) echo "$path_to_test" ;;
+            *"$distro_path/sys/"*) echo "$path_to_test" ;;
+            *"$distro_path/dev/"*) echo "$path_to_test" ;;
+            *)
+                # storage check could have been just one line like the above ones but wanted to have only
+                # the cases which prevents the unmount visible
+                echo "$storage_paths" | while read -r storage_path; do
+                    case "$path_to_test" in
+                        *"$storage_path/"*) echo "$path_to_test" ;;
+                        # everything else, ignore
+                        *) ;;
+                    esac
+                done
+            ;;
+        esac
+    done
+}
+
 chroot_distro_mount_system_point() {
     path_to_mount="$1"
     mount_point="$2"
@@ -975,28 +1005,8 @@ chroot_distro_unmount_system_point() {
         chroot_distro_find_all_mount_points "$mount_point/" | sort -r | xargs -I {} umount {} > /dev/null 2>&1
         # then hope for the best...
     fi
-    if ! umount "$mount_point"; then
-        echo "could not unmount $mount_point, distro is potentially running - if needed shutdown the distro, and try again"
-        echo
-        echo "open files under $mount_point:"
-        if [ "" != "$lsofpath" ]; then
-            lsof | grep -F "$mount_point/"
-        else
-            echo "Warning: supported lsof not found, run \`lsof | grep -F '$mount_point/'\` manually"
-        fi
-        echo "end of open files"
-        echo
-        echo "mount points under $mount_point:"
-        mount | grep -F "$mount_point/"
-        echo "end of mount points"
-        echo
-        echo "loopback devices under $mount_point:"
-        losetup -a | grep -F "$mount_point/"
-        echo "end of loopback devices"
-        echo
-        echo "If there is no open files, mount points or loopback devices, then check for anonymous inodes and inotify watches"
-        exit 1
-    fi
+    # no need to check for the success as the caller will take care of that
+    umount "$mount_point"
 }
 
 chroot_distro_unmount_system_points() {
@@ -1551,6 +1561,41 @@ chroot_distro_unmount() {
     fi
 
     chroot_distro_unmount_system_points "$distro_path" "$force"
+    mounts=$(mount | chroot_distro_output_system_mount_point_paths "$distro_path")
+    loopbacks=$(losetup -a | chroot_distro_output_system_mount_point_paths "$distro_path")
+    open_files=$(lsof | chroot_distro_output_system_mount_point_paths "$distro_path")
+    if [ "" != "$mounts" ] || [ "" != "$loopbacks" ] || [ "" != "$open_files" ] || chroot_distro_check_if_system_points_mounted "$distro_path"; then
+        # note: if there is still system mount points mounted without a valid reason, please create a bug report so that it can be investigated
+        echo 'distro is potentially running - if needed shutdown the distro, and unmount mounted folders'
+        echo
+        if [ "yes" != "$force" ]; then
+            echo 'You can try running unmount again with -f(--force) option to automatically close/unmount files/folders mentioned below.'
+            echo 'Please note, that using --force option may close more programs than intended, so use it with care.'
+        fi
+        echo
+        echo "open files under $distro_path (which affects unmounting, there may be more):"
+        if [ "" = "$lsofpath" ]; then
+            echo "Warning: supported lsof not found, run \`lsof | grep -F '$distro_path/'\` manually"
+        elif [ "" != "$open_files" ]; then
+            echo "$open_files"
+        fi
+        echo "end of open files"
+        echo
+        echo "mount points under $distro_path: (which affects unmounting, there may be more)"
+        if [ "" != "$mounts" ]; then
+            echo "$mounts"
+        fi
+        echo "end of mount points"
+        echo
+        echo "loopback devices under $distro_path: (which affects unmounting, there may be more)"
+        if [ "" != "$loopbacks" ]; then
+            echo "$loopbacks"
+        fi
+        echo "end of loopback devices"
+        echo
+        echo "If there is no open files, mount points or loopback devices, then check for anonymous inodes and inotify watches"
+        exit 1
+    fi
 }
 
 chroot_distro_command() {
