Unmount mount points without lazy unmount
Normal unmount should suffice, and don't use force for bind mounts,
it can cause problems with newer kernels by unmounting the underlying
transport channel thus causing other mount points which use the same
device to fail.

diff --git a/system/bin/chroot-distro b/system/bin/chroot-distro
--- a/system/bin/chroot-distro
+++ b/system/bin/chroot-distro
@@ -665,8 +665,8 @@ chroot_distro_unmount_system_point() {
         # nothing to do, already unmounted
         return
     fi
-    if ! umount -lf "$mount_point"; then
-        echo "could not unmount $mount_point, uninstall may need manual intervention, proceed with care"
+    if ! umount "$mount_point"; then
+        echo "could not unmount $mount_point, distro is potentially running - if needed shutdown the distro, and try again"
         exit 1
     fi
 }
