Update chroot-distro

diff --git a/system/bin/chroot-distro b/system/bin/chroot-distro
--- a/system/bin/chroot-distro
+++ b/system/bin/chroot-distro
@@ -74,7 +74,7 @@ if [ "" != "${check_env}" ]; then
     echo "Toybox version: $(toybox --version)"
 fi
 
-busyboxpath="$(command -v busybox 2> /dev/null )"
+busyboxpath="$(command -v busybox 2> /dev/null)"
 if [ -z "$busyboxpath" ]; then
     busyboxpath=''
     if [ -e /data/adb ]; then
@@ -169,7 +169,7 @@ fi
 
 busyboxlsofcaller=''
 busyboxlsof=''
-if [ "" != "$busyboxpath" ] && "$busyboxpath" lsof --help > /dev/null 2>&1 ; then
+if [ "" != "$busyboxpath" ] && "$busyboxpath" lsof --help > /dev/null 2>&1; then
     # prefer the version provided by the found busybox binary
     busyboxlsofcaller=true
     busyboxlsof=true
@@ -392,7 +392,7 @@ fixsuid() {
     # If the argument is "enable", write 1 to the suid file
     if [ "$1" = "enable" ]; then
         if [ "$suid_val" != "1" ]; then
-            echo 1 > "$suid_file" 
+            echo 1 > "$suid_file"
         else
             echo "fixsuid is enabled already"
             return 1
@@ -400,7 +400,7 @@ fixsuid() {
     # If the argument is "disable", write 0 to the suid file
     elif [ "$1" = "disable" ]; then
         if [ "$suid_val" != "0" ]; then
-            echo 0 > "$suid_file" 
+            echo 0 > "$suid_file"
         else
             echo "fixsuid is disabled already"
             return 1
@@ -412,13 +412,13 @@ fixsuid() {
 
     # If suid is disabled (0), remount /data with nosuid and nodev if needed
     if [ "$suid_val" = "0" ]; then
-        if grep -q '^/dev' /proc/mounts | grep -q ' /data ' | grep -wq "suid" ; then
-            mount -o remount,nodev,nosuid /data  || echo "Failed to remount /data with nosuid"
+        if grep -q '^/dev' /proc/mounts | grep -q ' /data ' | grep -wq "suid"; then
+            mount -o remount,nodev,nosuid /data || echo "Failed to remount /data with nosuid"
         fi
     # If suid is enabled (1), remount /data with suid and dev if needed
     elif [ "$suid_val" = "1" ]; then
-        if grep -q '^/dev' /proc/mounts | grep -q ' /data ' | grep -wq "nosuid" ; then
-            mount -o remount,dev,suid /data  || echo "Failed to remount /data with suid"
+        if grep -q '^/dev' /proc/mounts | grep -q ' /data ' | grep -wq "nosuid"; then
+            mount -o remount,dev,suid /data || echo "Failed to remount /data with suid"
         fi
     fi
 }
@@ -439,7 +439,7 @@ ram_bind() {
     # If the argument is "enable", write 1 to the ram bind file
     if [ "$1" = "enable" ]; then
         if [ "$ram_bind_val" != "1" ]; then
-            echo 1 > "$ram_bind_file" 
+            echo 1 > "$ram_bind_file"
         else
             echo "ram bind is enabled already"
             return 1
@@ -447,7 +447,7 @@ ram_bind() {
     # If the argument is "disable", write 0 to the ram bind file
     elif [ "$1" = "disable" ]; then
         if [ "$ram_bind_val" != "0" ]; then
-            echo 0 > "$ram_bind_file" 
+            echo 0 > "$ram_bind_file"
         else
             echo "ram bind is disabled already"
             return 1
@@ -474,7 +474,7 @@ android_bind() {
     # If the argument is "enable", write 1 to the android bind file
     if [ "$1" = "enable" ]; then
         if [ "$android_bind_val" != "1" ]; then
-            echo 1 > "$android_bind_file" 
+            echo 1 > "$android_bind_file"
         else
             echo "android bind is enabled already"
             return 1
@@ -482,7 +482,7 @@ android_bind() {
     # If the argument is "disable", write 0 to the android bind file
     elif [ "$1" = "disable" ]; then
         if [ "$android_bind_val" != "0" ]; then
-            echo 0 > "$android_bind_file" 
+            echo 0 > "$android_bind_file"
         else
             echo "android bind is disabled already"
             return 1
@@ -1066,7 +1066,7 @@ chroot_distro_unmount_system_point() {
        chroot_distro_force_unmount "$mount_point/" 
     fi
     # no need to check for the success as the caller will take care of that
-    if ! umount "$mount_point" ; then
+    if ! umount "$mount_point"; then
     echo "Warning: Failed to unmount $mount_point"
     fi
 }
@@ -1203,12 +1203,12 @@ prepare_chroot_distro() {
    echo "1007 aid_drm"
   } >> "$distro_path/etc/group"
    # Add usermod for _apt only if the distro is Debian-based
-   if chroot "$distro_path" /bin/id _apt >/dev/null 2>&1 ; then
+   if chroot "$distro_path" /bin/id _apt >/dev/null 2>&1; then
       chroot "$distro_path" /sbin/usermod -g 3003 -G 3003,3004 -a _apt 2>/dev/null
    fi
-   chroot "$distro_path" /sbin/usermod -G 3003 -a root 2>/dev/null 
+   chroot "$distro_path" /sbin/usermod -G 3003 -a root 2>/dev/null
    timezone="$(getprop persist.sys.timezone)"
-   chroot "$distro_path" /bin/ln -sf /usr/share/zoneinfo/"$timezone" /etc/localtime 2>/dev/null 
+   chroot "$distro_path" /bin/ln -sf /usr/share/zoneinfo/"$timezone" /etc/localtime 2>/dev/null
 } 
 
 chroot_distro_install() {
@@ -1401,7 +1401,7 @@ chroot_distro_backup() {
         fi
         (
             cd "$chroot_distro_path" || chroot_distro_exit 1;
-            if ! tar -caf "$backup_path" "$distro" 2>/dev/null ; then
+            if ! tar -caf "$backup_path" "$distro" 2>/dev/null; then
                 echo "Error: creating the backup failed"
                 chroot_distro_exit 5
             fi
@@ -1414,7 +1414,7 @@ chroot_distro_backup() {
         fi
         (
             cd "$chroot_distro_path" || chroot_distro_exit 1;
-            if ! tar -caf "$absolute_custom_path" "$distro" 2>/dev/null ; then
+            if ! tar -caf "$absolute_custom_path" "$distro" 2>/dev/null; then
                 echo "Error: creating the backup failed"
                 chroot_distro_exit 5
             fi
@@ -1509,7 +1509,7 @@ chroot_distro_restore() {
     if [ "." = "$rootdir" ]; then
         # backup has relative path, restoring is not a problem
         mkdir -p "$distro_path"
-        if ! tar -xf "$backup_path" -C "$distro_path/" 2>/dev/null ; then
+        if ! tar -xf "$backup_path" -C "$distro_path/" 2>/dev/null; then
             echo "Error: Unpacking the archive failed"
             chroot_distro_exit 5
         fi
@@ -1520,7 +1520,7 @@ chroot_distro_restore() {
         # fill the internal storage. There is also possibility of using wrong backup.
         (
             cd /
-            if ! tar -xf "$backup_path" 2>/dev/null ; then
+            if ! tar -xf "$backup_path" 2>/dev/null; then
                 echo "Error: Unpacking the archive failed"
                 chroot_distro_exit 5
             fi
@@ -1540,7 +1540,7 @@ chroot_distro_restore() {
         # new format backups
         (
             cd "$chroot_distro_path" || chroot_distro_exit 1;
-            if ! tar -xf "$backup_path" 2>/dev/null ; then
+            if ! tar -xf "$backup_path" 2>/dev/null; then
                 echo "Error: Unpacking the archive failed"
                 chroot_distro_exit 5
             fi
